// explain_datecs_error: Datecs fiscal printer / cash register error codes (src/lib/kb/datecs-errors.json,
// generated by scripts/build-datecs-kb.mjs).

import type { ToolDef } from "../types.ts";
import { normalize, tokenize } from "../text.ts";
import { trackedUrl } from "../links.ts";
import { readOnly } from "./kb.ts";

const NAME = "explain_datecs_error";
export const DATECS_PAGE = "/ghid/erori-datecs";

export interface DatecsCode {
  en: string;
  ro: string | null;
  group: string | null;
  source: string;
}
export interface DatecsHint {
  key: string;
  title: string;
  steps: string[];
  status_bit?: string;
}
export interface DatecsKb {
  codes: Record<string, DatecsCode>;
  hints: Record<string, DatecsHint>;
}

/** Anchor used on /ghid/erori-datecs for one code: "-111008" -> "cod-111008". */
export function datecsAnchor(code: string): string {
  return `cod-${code.replace(/^-/, "")}`;
}

/** "-111008", "111008", "ERR 111008", "eroarea -111.008" -> the KB key ("-111008"), or null. */
export function findDatecsCode(kb: DatecsKb, input: string): string | null {
  const m = /(\d[\d.]*)/.exec(String(input ?? ""));
  if (!m) return null;
  const digits = m[1].replace(/\./g, "").replace(/^0+(?=\d)/, "");
  if (!/^\d{1,7}$/.test(digits)) return null;
  const neg = `-${digits}`;
  // Almost every code is negative; users often drop the minus sign.
  if (kb.codes[neg]) return neg;
  return kb.codes[digits] ? digits : null;
}

/** Codes whose English or Romanian text matches the words in the query. */
export function searchDatecsText(kb: DatecsKb, text: string, limit = 5): string[] {
  const tokens = tokenize(text);
  if (!tokens.length) return [];
  return Object.entries(kb.codes)
    .map(([code, c], i) => {
      const hay = ` ${normalize(`${c.en} ${c.ro ?? ""} ${kb.hints[code]?.title ?? ""}`)} `;
      const hits = tokens.filter((t) => hay.includes(` ${t}`)).length;
      return { code, i, score: hits + (hits > 0 && kb.hints[code] ? 0.5 : 0) };
    })
    .filter((x) => x.score >= Math.max(1, Math.ceil(tokens.length / 2)))
    .sort((a, b) => b.score - a.score || a.i - b.i)
    .slice(0, limit)
    .map((x) => x.code);
}

export function codeMd(kb: DatecsKb, code: string): string {
  const c = kb.codes[code];
  const h = kb.hints[code];
  const url = trackedUrl(`${DATECS_PAGE}#${datecsAnchor(code)}`, NAME);
  const lines = [
    `**Eroare Datecs ${code}**`,
    "",
    `- Romana: ${c.ro ?? "(fara traducere oficiala)"}`,
    `- English: ${c.en}`,
    c.group ? `- Categorie: ${c.group}` : null,
  ];
  if (h) {
    lines.push("", `**Ce faci: ${h.title}**`, ...h.steps.map((s, i) => `${i + 1}. ${s}`));
    if (h.status_bit) lines.push("", `Bit de stare Datecs: ${h.status_bit}.`);
  } else {
    lines.push("", "Nu avem pasi verificati pentru acest cod. Noteaza codul si contacteaza service-ul autorizat sau furnizorul programului POS.");
  }
  lines.push("", `Toate erorile Datecs: ${url}`);
  return lines.filter((l) => l !== null).join("\n");
}

export function createDatecsTool(kb: DatecsKb): ToolDef {
  return {
    name: NAME,
    title: "Explica o eroare Datecs (casa de marcat)",
    description:
      "Explain a Datecs fiscal printer / cash register error code (eroare casa de marcat Datecs, imprimanta fiscala " +
      "FP-700 / DP, cod eroare de tipul -111008 sau 111008) in Romanian and English, with practical fix steps for " +
      "common errors: lipsa hartie, capac deschis, raport Z dupa 24 de ore, data/ora gresita, grupa TVA invalida, " +
      "memorie fiscala plina, eroare de sintaxa. Give `code` when known, else `text` with the message shown.",
    inputSchema: {
      type: "object",
      properties: {
        code: { type: "string", minLength: 1, maxLength: 30, description: "Codul erorii, de ex. \"-111008\", \"111008\", \"ERR 111008\"" },
        text: { type: "string", minLength: 2, maxLength: 200, description: "Mesajul afisat, daca nu ai codul" },
      },
      additionalProperties: false,
    },
    annotations: readOnly(false),
    async handler(args) {
      const pageUrl = trackedUrl(DATECS_PAGE, NAME);
      const codeIn = typeof args.code === "string" ? args.code : "";
      const textIn = typeof args.text === "string" ? args.text : "";
      if (!codeIn && !textIn) {
        return { text: "Spune-mi codul erorii (de ex. -111008) sau mesajul afisat de casa.", isError: true };
      }
      const code = codeIn ? findDatecsCode(kb, codeIn) : null;
      if (code) {
        return {
          text: codeMd(kb, code),
          structured: { code, ...kb.codes[code], hint: kb.hints[code] ?? null, url: trackedUrl(`${DATECS_PAGE}#${datecsAnchor(code)}`, NAME) },
        };
      }
      const matches = searchDatecsText(kb, textIn || codeIn);
      if (!matches.length) {
        return {
          text: `Nu am gasit ${codeIn ? `codul "${codeIn.slice(0, 30)}"` : "o eroare potrivita"} in lista Datecs. Verifica codul complet afisat de casa (de obicei 6 cifre, cu minus). Lista completa: ${pageUrl}`,
          structured: { code: null, matches: [], url: pageUrl },
        };
      }
      if (matches.length === 1) {
        const only = matches[0];
        return { text: codeMd(kb, only), structured: { code: only, ...kb.codes[only], hint: kb.hints[only] ?? null } };
      }
      const list = matches.map((c) => `- ${c}: ${kb.codes[c].ro ?? kb.codes[c].en}${kb.hints[c] ? " (avem pasi de rezolvare)" : ""}`);
      return {
        text: `Coduri posibile:\n${list.join("\n")}\n\nSpune-mi codul exact pentru pasii de rezolvare. Lista completa: ${pageUrl}`,
        structured: { code: null, matches: matches.map((c) => ({ code: c, ...kb.codes[c] })), url: pageUrl },
      };
    },
  };
}
